[workspace]
authors = ["jczimm <jczimm@jczimm.com>"]
channels = ["conda-forge"]
name = "xiang2023"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
r-base = ">=4.5.1,<4.6"
quarto = ">=1.8.25,<2"
r-knitr = ">=1.50,<2"
r-rmarkdown = ">=2.30,<3"
